account/urls.py
from django.urls import path
from account.views import ( login_view,
    home_view,
    register_view,
    logout_view,
    edit_account_view,
    profile_view
)

app_name = 'account'

urlpatterns = [
    path("",home_view,name="home"),
    path('login/',login_view,name="login"),
    path("register/",register_view,name="register"),
    path("logout",logout_view,name='logout'),
    path('<user_id>/edit/', edit_account_view, name="edit"),
    path('<user_id>/profile/',profile_view,name='profile')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    # path('account/', include('django.contrib.auth.urls')),



        # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <title></title>
  </head>
  <body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container">
        <a class="navbar-brand" href="{% url 'account:home' %}">My Site</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'account:home' %}">Home</a>

          </div>
        </div>


        {% if user.is_authenticated %}
        <div class="dropdown">
          <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

              <span>Hi {{user.username}}</span>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'account:profile' user_id=user.id %}">Profile</a>
              <a class="dropdown-item" href="{% url 'account:edit' user_id=user.id %}">Edit Profile</a>
            <a class="nav-item nav-link" href="{% url 'account:logout' %}">Logout</a>
          </div>
      </div>

        {% else %}
          <a class="nav-item nav-link" href="{% url 'account:login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'account:register' %}">Register</a>
        {% endif %}

      </nav>
    </header>

    </div>

    <div class="container">


      {% block content %}

      {% endblock %}

    </div>






    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
  <h1>Home</h1>
{% for item in queryset %}
    {{ item.id }}-{{ item.email }}<br>
{% endfor %}

{% endblock %}